using System;
using System.IO;
using System.Threading.Tasks;

namespace CryptoExchange.Net.Authentication
{
    /// <summary>
    /// Api credentials, used to sign requests accessing private endpoints
    /// </summary>
    public class ApiCredentials
    {
        /// <summary>
        /// The api key / label to authenticate requests
        /// </summary>
        public string Key { get; set; }

        /// <summary>
        /// The api secret or private key to authenticate requests
        /// </summary>
        public string Secret { get; set; }

        /// <summary>
        /// The api passphrase. Not needed on all exchanges
        /// </summary>
        public string? Pass { get; set; }

        /// <summary>
        /// Type of the credentials
        /// </summary>
        public ApiCredentialsType CredentialType { get; set; }

        /// <summary>
        /// Create Api credentials providing an api key and secret for authentication
        /// </summary>
        /// <param name="key">The api key / label used for identification</param>
        /// <param name="secret">The api secret or private key used for signing</param>
        /// <param name="pass">The api pass for the key. Not always needed</param>
        /// <param name="credentialType">The type of credentials</param>
        public ApiCredentials(string key, string secret, string? pass = null, ApiCredentialsType credentialType = ApiCredentialsType.Hmac)
        {
            if (string.IsNullOrEmpty(key) || string.IsNullOrEmpty(secret))
                throw new ArgumentException("Key and secret can't be null/empty");

            CredentialType = credentialType;
            Key = key;
            Secret = secret;
            Pass = pass;
        }

        /// <summary>
        /// Create API credentials using an API key and secret generated by the server
        /// </summary>
        public static ApiCredentials HmacCredentials(string apiKey, string apiSecret, string? pass)
        {
            return new ApiCredentials(apiKey, apiSecret, pass, ApiCredentialsType.Hmac);
        }

        /// <summary>
        /// Create API credentials using an API key and an RSA private key in PEM format
        /// </summary>
        public static ApiCredentials RsaPemCredentials(string apiKey, string privateKey)
        {
            return new ApiCredentials(apiKey, privateKey, credentialType: ApiCredentialsType.RsaPem);
        }

        /// <summary>
        /// Create API credentials using an API key and an RSA private key in XML format
        /// </summary>
        public static ApiCredentials RsaXmlCredentials(string apiKey, string privateKey)
        {
            return new ApiCredentials(apiKey, privateKey, credentialType: ApiCredentialsType.RsaXml);
        }

        /// <summary>
        /// Create API credentials using an API key and an Ed25519 private key
        /// </summary>
        public static ApiCredentials Ed25519Credentials(string apiKey, string privateKey)
        {
            return new ApiCredentials(apiKey, privateKey, credentialType: ApiCredentialsType.Ed25519);
        }

        /// <summary>
        /// Load a key from a file
        /// </summary>
        public static string ReadFromFile(string path)
        {
            using var fileStream = File.OpenRead(path);
            using var streamReader = new StreamReader(fileStream);
            return streamReader.ReadToEnd();
        }

        /// <summary>
        /// Copy the credentials
        /// </summary>
        /// <returns></returns>
        public virtual ApiCredentials Copy()
        {
            return new ApiCredentials(Key, Secret, Pass, CredentialType);
        }
    }
}
